### ISSUE TITLE
분업 역할 나누기

### ISSUE THREAD

**Issue by checkIn97** [checkIn97/Diet-Project#1]
프로젝트 역할을 나눠봅시다.

- [x]  서로 무엇을 하면 좋을지 의견을 나눠주세요
- [ ] 정해지면 깃허브 프로젝트로 남겨주세요

**Comment by checkIn97** [comment]
의견 나눴습니다.

**Comment by checkIn97** [comment]
참고 사이트 링크입니다. (6meal) : UFC 김동현 선수 팀에서 제작한 식단관리용 음식 추천 웹사이트(AI 활용)
https://6meal.co.kr/?utm_source=google&utm_medium=cpc&utm_campaign=G_SA_sixmeal&utm_content=%EB%B8%8C%EB%9E%9C%EB%93%9CK&utm_term=&gad_source=1&gclid=EAIaIQobChMIrpTolaXGhQMVaNUWBR15HwD2EAAYASAAEgLfsfD_BwE

**Comment by checkIn97** [comment]
참고하세요 : 연령별, 지역별, 연도별 영양소 필요섭취량 데이터

https://www.khidi.or.kr/kps/dhraStat/result5?menuId=MENU01656&gubun=age1&year=2017

**Comment by SHU-Webbb** [comment]
프론트: 은희님, 두영님
백: 나머지 분들

**Comment by SHU-Webbb** [comment]
산이
회원 - 로그인, 회원가입, 회원탈퇴, 회원정보 수정, 마이 페이지

재우님
관리자 - 푸드테이블관리, 회원관리(수정,삭제), 게시글(삭제)

시우
커뮤니티 - 게시글 목록(검색), 게시글 (작성,수정,삭제), 댓글

상호님.
food 검색창 -  food 리스트, food 상세보기(좋아요)
식단추천 - 정보,목적입력, 결과 출력(상세보기), 마이페이지에 추가,

두영님,은희님
프론트엔드 정리...
