### ISSUE TITLE
요구정의서

### ISSUE THREAD

**Issue by checkIn97** [checkIn97/Diet-Project#15]
밑에 Add a comment 칸 밑에 클립모양 아이콘과 Paste, drop, or click to add files 버튼 누르면 파일 첨부 가능하십니다
본인이 맡은 부분 정의서 작성해서 올려주시면 제가 취합하겠습니다!

**Comment by SHU-Webbb** [comment]
커뮤니티 부분 요구사항 정의서 파일 첨부합니다.


[요구사항정의서_V1.0(이시우).xls](https://github.com/checkIn97/Diet-Project/files/15104556/_V1.0.xls)

**Comment by SHU-Webbb** [comment]
커뮤니티부분 요구정의서 파일 첨부합니다.

[요구사항정의서_V1.0(이시우).xls](https://github.com/checkIn97/Diet-Project/files/15104569/_V1.0.xls)

**Comment by kjw1682** [comment]
[foodnavi.txt](https://github.com/checkIn97/Diet-Project/files/15104599/foodnavi.txt)

메모장으로 첨부드립니다.

**Comment by Sangho-Do** [comment]
[요구사항정의서_V1.0 (도상호).xlsx](https://github.com/checkIn97/Diet-Project/files/15104785/_V1.0.xlsx)

검색 및 추천 관련한 부분 적었습니다.
단어나 기타 등등 적당히 수정하셔도 됩니다.

**Comment by eunhe** [comment]
요구사항정의서_V1.0 (김은희).xlsx[_V1.0.xls](https://github.com/checkIn97/Diet-Project/files/15107164/_V1.0.xls)

**Comment by checkIn97** [comment]
<프로젝트 1차 구현>
구현 기간 : 4/30 ~ 5/29
구현 내용 발표 : 5/30

요구사항정의서, ERD 제출 5/3 까지

**Comment by donbacksu** [comment]
[요구사항정의서_V1.0_FoodNavi_프론트엔드.xlsx](https://github.com/checkIn97/Diet-Project/files/15157066/_V1.0_FoodNavi_.xlsx)

**Comment by checkIn97** [comment]
[요구사항정의서_건강한한끼추천시스템(통합).xlsx](https://github.com/checkIn97/Diet-Project/files/15157101/_.xlsx)

**Comment by Sangho-Do** [comment]
[도메인 정리(202405011307).txt](https://github.com/checkIn97/Diet-Project/files/15173531/202405011307.txt)
유저의 관심사 등은 아직 추가되지 않았습니다.

**Comment by checkIn97** [comment]
요구정의서 취합 완료
